services:
  php:
    build: ./docker/php
    ports:
      - ${APP_PORT:-80}:80
      - ${APP_HTTPS_PORT:-443}:443
      - "5173:5173"
    environment:
      TZ: 'Asia/Tokyo'
      CADDY_GLOBAL_OPTIONS: "debug"
    volumes:
      - .:/var/www/html
      - ./docker/php/php.dev.ini:/usr/local/etc/php/php.ini
      - ./docker/php/log:/var/log
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - postgres
    tty: true
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPASSWORD: postgres
      POSTGRES_DB: main
      TZ: "Asia/Tokyo"
    ports:
      - ${PG_PORT:-5432}:5432
    volumes:
      - db_volume:/var/lib/postgresql/data
volumes:
  db_volume:
  caddy_data:
  caddy_config:
